#!/bin/bash

###
### Script for sourcing a ros environment 
###

# get starting directory
CWD=$(pwd)
DIR=$CWD
NOTFOUND=true

echo " "

# search recursively through folders until we run into the homedirectory
while test $CWD != $HOME && $NOTFOUND ; do
  if [ -f "$CWD/wet/devel/setup.bash" -o -f "$CWD/devel/setup.bash" ] ;
  then
    if [ -f "$CWD/../setup.bash" ] ;
    then
      source $CWD/../setup.bash
    elif [ -f "$CWD/setup.bash" ] ;
    then
      source $CWD/setup.bash
    else
      source $CWD/devel/setup.bash
    fi
    echo "sourced workspace in $CWD"
    NOTFOUND=false
  else  
    pushd .. > /dev/null
    CWD=$(pwd)
  fi
done

# if we didn't find a catkin workspace source bashrc, just in case
if $NOTFOUND;
then
  echo "Not in catkin workspace, sourcing .bashrc"
  source ~/.bashrc
fi

echo " "

# get back old working directory and clear directory stack
pushd $DIR > /dev/null
dirs -c > /dev/null
